services:
  nginx:
    build: ./nginx/
    container_name: nginx-container
    ports:
      - 80:80
    links:
      - php
    volumes_from:
      - app-data

  php:
    build: ./php/
    container_name: php-container
    expose:
      - 9000
    links:
      - database
    volumes_from:
      - app-data

  database:
    image: mysql:5.7
    container_name: database
    volumes_from:
      - mysql-data
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    depends_on:
      - database
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8080:80"

  app-data:    
    image: php:7.0-fpm
    container_name: app-data-container
    volumes:
      - E:\Dev\mysqlphpngnixcompose\www\html:/var/www/html/
    command: "true"

  mysql-data:
    image: mysql:5.7
    container_name: mysql-data-container
    volumes:
      - /var/lib/mysql
    command: "true"